doctrine_migrations:
    migrations_paths:
        'Migrations\V1\Users': '%kernel.project_dir%/migrations/v1_database_scheme/Users'
        'Migrations\V1\Different': '%kernel.project_dir%/migrations/v1_database_scheme/Different'
    enable_profiler: false